# For the annotation.
QUESTIONS_PER_HIT = 5
MIN_ANSWERS_PER_QUESTION = 2

# For the review.
MIN_ACCEPTABLE_ANSWERS_PER_QUESTION = MIN_ANSWERS_PER_QUESTION * .75
REVIEW_SAMPLE_SIZE_PER_WORKER = QUESTIONS_PER_HIT * 2

# For the bonuses.
MAX_COVERED_ANSWERS_PER_QUESTION_BONUS_TYPE_1 = 3
PAY_PER_ANSWER_BONUS_TYPE_1 = 0.01
