# For the annotation.
QUESTIONS_PER_HIT = 5
MIN_ANSWERS_PER_QUESTION = 2

# For the review.
AUTO_APPROVE_WORKER_ID_DENY_LIST = {"3E9ZFLPWOXRVU3D5TC98SM0RRILIXK"}
MIN_ACCEPTABLE_ANSWERS_PER_QUESTION_1 = MIN_ANSWERS_PER_QUESTION * .75
MIN_ACCEPTABLE_ANSWERS_PER_QUESTION_2 = MIN_ANSWERS_PER_QUESTION / 2
MIN_QUESTION_COUNT_FOR_THRESHOLD_2 = QUESTIONS_PER_HIT * 5
REVIEW_SAMPLE_SIZE_PER_WORKER = QUESTIONS_PER_HIT * 2

# For the bonuses.
MAX_COVERED_ANSWERS_PER_QUESTION_BONUS_TYPE_1 = 3
PAY_PER_ANSWER_BONUS_TYPE_1 = 0.01
PAY_PER_HIT_BONUS_TYPE_2 = 0.2
