from unittest import TestCase

from lqam.core.noun_phrases import create_spacy_model, is_noun_phrase_like


class TestNounPhrases(TestCase):
    def test_is_noun_phrase(self):
        questions_answers_nps = [  # Note all these have been manually inspected.
            ("A person is cleaning a window with _____.", "18 inch squeegee", True),
            ("Two strong men are fighting with each other in _____.", "a battle of fists", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a beam", True),
            ("Two strong men are fighting with each other in _____.", "a boxing arena", True),
            ("Two strong men are fighting with each other in _____.", "a boxing match", True),
            ("Two strong men are fighting with each other in _____.",
             "a boxing ring with george foreman knocking down his opponent", False),  # The PP is actually attached
            # to the verb.
            ("Two strong men are fighting with each other in _____.", "a boxing ring", True),
            ("Two strong men are fighting with each other in _____.", "a boxing stadium", True),
            ("_____ gives a demonstration of a song on piano.", "a boy", True),
            ("_____ gives a demonstration of a song on piano.", "a casual player", True),
            ("A person is cleaning a window with _____.", "a cleaning instrument", True),
            ("A person is cleaning a window with _____.", "a cleaning utensil", True),
            ("Two strong men are fighting with each other in _____.", "a crowded venue", True),
            ("Two strong men are fighting with each other in _____.", "a fight", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a flashlight of some sort",
             True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a flashlight", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a handheld flashlight",
             True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a headlamp on the caver",
             True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a headlamp", True),
            ("Two strong men are fighting with each other in _____.", "a heated battle", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a helmet-mounted light",
             True),
            ("A person uses _____ to dig into an ice face and climb it.", "a hook", True),
            ("Two strong men are fighting with each other in _____.", "a horrible fashion", True),
            ("_____ gives a demonstration of a song on piano.", "a keyboard enthusiast", True),
            ("_____ gives a demonstration of a song on piano.", "a keyboard hobbyist", True),
            ("_____ gives a demonstration of a song on piano.", "a keyboard instructor", True),
            ("_____ gives a demonstration of a song on piano.", "a keyboardist", True),
            ("Footage of rock formations taken at night with _____ as the light source.",
             "a lamp used by the adventurer", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a lamp", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a light", True),
            ("A person is cleaning a window with _____.", "a long-poled squeegee", True),
            ("_____ gives a demonstration of a song on piano.", "a male instructor", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a man holding a flashlight",
             True),
            ("_____ gives a demonstration of a song on piano.", "a man shows us how to play a piano and", False),
            ("_____ gives a demonstration of a song on piano.", "a man", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a mini torchlight", True),
            ("A person is cleaning a window with _____.", "a mop", True),
            ("Two strong men are fighting with each other in _____.", "a packed arena", True),
            # ("a person", True),
            # ("a phone", True),
            ("_____ gives a demonstration of a song on piano.", "A pianist shows how to get a different sound and",
             False),
            ("_____ gives a demonstration of a song on piano.", "a pianist", True),
            ("_____ gives a demonstration of a song on piano.", "a piano instructor", True),
            ("_____ gives a demonstration of a song on piano.", "a piano player", True),
            ("_____ gives a demonstration of a song on piano.", "a piano teacher", True),
            ("A person uses _____ to dig into an ice face and climb it.", "a pick", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a pocket flashlight", True),
            # ("a portable device", True),
            # ("a professional competition", True),
            # ("a professional", True),
            # ("a protective layer of styrofoam", True),
            ("Two strong men are fighting with each other in _____.", "a ring", True),
            # ("a rubber blade on a pole", True),
            ("A person is cleaning a window with _____.", "a rubber squeegee", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a searchlight", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a small flashlight", True),
            ("A person is cleaning a window with _____.", "a sponge", True),
            ("A person is cleaning a window with _____.", "a squeegee", True),
            ("A person is cleaning a window with _____.", "a sweeper", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a tactical flashlight",
             True),
            # ("a teacher", True),
            ("A person is cleaning a window with _____.", "a tool on a stick", True),
            ("A person is cleaning a window with _____.", "a tool", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "a torchlight", True),
            # ("a tutor", True),
            ("A person is cleaning a window with _____.", "a wagtail squeegee", True),
            # ("a youtuber", True),
            # ("ample protection", True),
            # ("an apparatus", True),
            # ("an arena", True),
            # ("an attempt to see who wins", True),
            ("A person uses _____ to dig into an ice face and climb it.", "an axe", True),
            ("A person uses _____ to dig into an ice face and climb it.", "an ice climbing pick", True),
            ("A person uses _____ to dig into an ice face and climb it.", "an ice pick", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "an led lamp", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "an led torch", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "an unsteady flashlight",
             True),
            # ("an youtuber", True),
            # ("applying", True),
            # ("arranger", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "artificial light", True),
            # ("artist", True),
            # ("athleticism", True),
            # ("automotive maintenance information", True),
            ("A person uses _____ to dig into an ice face and climb it.", "bladed shoes", True),
            ("A person uses _____ to dig into an ice face and climb it.", "boots with metal prongs", True),
            ("A person uses _____ to dig into an ice face and climb it.", "boots with spikes", True),
            ("Two strong men are fighting with each other in _____.", "boxing match", True),
            ("Two strong men are fighting with each other in _____.", "boxing", True),
            # ("A person is cleaning a window with _____.", "broom with cloth at the end", True),  # FIXME
            ("A person is cleaning a window with _____.", "brush", True),
            # ("brute strength", True),
            # ("car parts", True),
            # ("cautioning how to hammer", True),
            ("A person uses _____ to dig into an ice face and climb it.", "cleats", True),
            ("A person uses _____ to dig into an ice face and climb it.", "climbing boots", True),
            ("A person uses _____ to dig into an ice face and climb it.", "climbing gear", True),
            ("A person uses _____ to dig into an ice face and climb it.", "climbing implements", True),
            ("Two strong men are fighting with each other in _____.", "competitive boxing", True),
            # ("competitive run", True),
            # ("competitive spirit", True),
            # ("composer", True),
            ("A person uses _____ to dig into an ice face and climb it.", "crampons", True),
            ("A man puts _____ around a product in a cardboard box.", "cushioning material", True),
            # ("downhill skiing", True),
            # ("elegance", True),
            # ("enthralling run", True),
            # ("escapades", True),
            # ("event time", True),
            # ("extra protection", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "flashlight on helmet", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "flashlight", True),
            # ("flat metal objects", True),
            ("A man puts _____ around a product in a cardboard box.", "foam blocks and sheets", True),
            ("A man puts _____ around a product in a cardboard box.", "foam fillers", True),
            ("A man puts _____ around a product in a cardboard box.", "foam sheets", True),
            ("A man puts _____ around a product in a cardboard box.", "foam", True),
            # ("front of the audience", True),
            # ("gavin degraw", True),
            # ("hammering in", True),
            # ("he wants to hammer it in", False),
            ("Footage of rock formations taken at night with _____ as the light source.", "headlamp", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "headlight", True),
            # ("heated combat", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "helmet light", True),
            ("Footage of rock formations taken at night with _____ as the light source.", "helmet torch", True),
            # ("his actions", True),
            ("A person uses _____ to dig into an ice face and climb it.", "his boots", True),
            ("A person uses _____ to dig into an ice face and climb it.", "his feet", True),
            ("A person uses _____ to dig into an ice face and climb it.", "his hands and feet", True),
            # ("his intentions", True),
            # ("his methods", True),
            ("A person uses _____ to dig into an ice face and climb it.", "his own hands", True),
            # ("his plan", True),
            # ("how it works", True),
            # ("how to add a wheel stud", True),
            # ("how to attach", True),
            # ("how to change a tire", True),
            # ("how to change a wheel stud", True),
            ("A person uses _____ to dig into an ice face and climb it.", "ice boots", True),
            ("A person uses _____ to dig into an ice face and climb it.", "ice climbing boots", True),
            ("A person uses _____ to dig into an ice face and climb it.", "ice grippers", True),
            ("A person uses _____ to dig into an ice face and climb it.", "ice picks", True),
            ("A person uses _____ to dig into an ice face and climb it.", "kicking motions", True),
            ("A man puts _____ around a product in a cardboard box.", "loose styrofoam packing closely", False),
            # ("man", True),
            ("A person is cleaning a window with _____.", "mop", True),
            ("_____ gives a demonstration of a song on piano.", "musician", True),
            # ("nuts", True),
            # ("olympic run", True),
            # ("olympic skiing event", True),
            # ("order to see which one will be the victor", True),
            ("A man puts _____ around a product in a cardboard box.", "package stuffing", True),
            ("A man puts _____ around a product in a cardboard box.", "packaging cushion", True),
            ("A man puts _____ around a product in a cardboard box.", "packaging foam", True),
            ("A man puts _____ around a product in a cardboard box.", "packaging material", True),
            ("A man puts _____ around a product in a cardboard box.", "packing foam", True),
            ("A man puts _____ around a product in a cardboard box.", "packing material", True),
            ("A man puts _____ around a product in a cardboard box.", "packing materials", True),
            ("A man puts _____ around a product in a cardboard box.", "padding material", True),
            # ("padding", True),
            ("_____ gives a demonstration of a song on piano.", "pianist", True),
            ("A man puts _____ around a product in a cardboard box.", "pieces of styrofoam", True),
            ("A man puts _____ around a product in a cardboard box.", "pink styrofoam", True),
            # ("practice run", True),
            ("A man attaches a washer to a large machine and describes _____.", "properly installing washers", True),
            # ("protection", True),
            ("A man attaches a washer to a large machine and describes _____.", "pulling on the washer", True),
            # ("pulling", True),
            # ("putting it on the stud", True),
            # ("race", True),
            ("_____ of a professional skier.", "raw footage", True),
            ("_____ of a professional skier.", "recording", True),
            ("A man attaches a washer to a large machine and describes _____.", "repairing a tire", True),
            ("Two strong men are fighting with each other in _____.", "ring", True),
            ("A man puts _____ around a product in a cardboard box.", "safety cushion", True),
            ("A person is cleaning a window with _____.", "scraper on a pole", True),
            ("A man puts _____ around a product in a cardboard box.", "several styrofoam products", True),
            ("A person uses _____ to dig into an ice face and climb it.", "shoe pics", True),
            ("A person uses _____ to dig into an ice face and climb it.", "shoes", True),
            ("Two strong men are fighting with each other in _____.", "shorts", True),
            # ("ski run", True),
            # ("skiing course", True),
            # ("slalom", True),
            ("_____ of a professional skier.", "slow-motion video", True),
            ("A person uses _____ to dig into an ice face and climb it.", "snow boots", True),
            ("A person uses _____ to dig into an ice face and climb it.", "snow shoes", True),
            # ("some padding", True),
            ("A man puts _____ around a product in a cardboard box.", "some styrofoam", True),
            # ("somebody on camera", True),
            ("A person uses _____ to dig into an ice face and climb it.", "special spiked boots", True),
            ("A person uses _____ to dig into an ice face and climb it.", "spiked boots", True),
            ("A person uses _____ to dig into an ice face and climb it.", "spikes", True),
            ("A person is cleaning a window with _____.", "squeegee on a pole", True),
            ("A person is cleaning a window with _____.", "squeegee", True),
            # ("A man puts _____ around a product in a cardboard box.", "styrofoam packing", True),  # FIXME: ambiguous
            ("A man puts _____ around a product in a cardboard box.", "styrofoam to act as a safeguard",
             False),  # The PP is attached to the verb.
            ("A man puts _____ around a product in a cardboard box.", "styrofoam", True),
            ("A person is cleaning a window with _____.", "telescoping squeegee", True),
            ("A man attaches a washer to a large machine and describes _____.", "the 240x wheel stud changing process",
             True),
            ("Two strong men are fighting with each other in _____.", "the boxing championship", True),
            ("Two strong men are fighting with each other in _____.", "the boxing ring", True),
            ("Two strong men are fighting with each other in _____.", "the championship", True),
            ("A man attaches a washer to a large machine and describes _____.", "the correct installation method",
             True),
            # ("the moves", True),
            ("_____ gives a demonstration of a song on piano.", "the musician", True),
            ("A man attaches a washer to a large machine and describes _____.", "the objects being applied", True),
            # ("the person in the video", True),
            # ("the person", True),
            ("_____ gives a demonstration of a song on piano.", "the pianist", True),
            ("A man attaches a washer to a large machine and describes _____.", "the pieces used", True),
            ("A person uses _____ to dig into an ice face and climb it.", "the pointed end of an ice axe", True),
            # ("the poise", True),
            ("A man attaches a washer to a large machine and describes _____.", "the process", True),
            ("A man attaches a washer to a large machine and describes _____.", "the right way to install it", True),
            ("Two strong men are fighting with each other in _____.", "the ring", True),
            # ("the showmanship", True),
            # ("the skier is a prime example", False),
            # ("the squared circle", True),
            # ("the tools used", True),
            # ("the trials", True),
            # ("the way to do it", True),
            # ("thermocol sheets", True),
            ("_____ of a professional skier.", "this is a slow motion view", False),
            # ("this is a stunning performance", False),
            # ("this is one example", False),
            ("_____ of a professional skier.", "this video is a slow motion angle", False),
            ("Footage of rock formations taken at night with _____ as the light source.", "torch", True),
            # ("tricks", True),
            # ("turning", True),
            # ("turns", True),
            ("_____ of a professional skier.", "video", True),
            # ("view of the camera", True),
            ("A person is cleaning a window with _____.", "washers", True),
            ("A person is cleaning a window with _____.", "water and squeegee", True),
            ("A person is cleaning a window with _____.", "window cleaner", True),
            ("A person is cleaning a window with _____.", "window cleaning device on a pole", True),
            ("A person is cleaning a window with _____.", "window cleaning tools", True),
            ("A person is cleaning a window with _____.", "wiper", True),
            # ("with gloves on", False),
            ("_____ gives a demonstration of a song on piano.", "you can see that the pianist", False),
            # ("you can see this can hurt the legs and knees", False),

            # ("_____ a dog.", "A cat and", False), FIXME: there shouldn't be more dependents below the phrase.
            ("_____ how he puts together a small finished wood shelf.", "A man video tapes", False),
        ]

        texts_starts_ends_and_nps = [(question.replace("_____", answer), (start := question.index("_____")),
                                      start + len(answer), np)
                                     for question, answer, np in questions_answers_nps]

        spacy_model = create_spacy_model(prefer_gpu=True)
        docs = spacy_model.pipe(text for text, _, _, _ in texts_starts_ends_and_nps)

        for doc, (_, start, end, expected_np) in zip(docs, texts_starts_ends_and_nps):
            actual_np = is_noun_phrase_like(doc, start, end)
            self.assertEqual(expected_np, actual_np,
                             f"\"{doc}\" noun phrase value was expected to be {expected_np} but the actual value is"
                             f" {actual_np}.")
