from unittest import TestCase

from lqam.core.noun_phrases import create_spacy_model, is_noun_phrase_like


class TestNounPhrases(TestCase):
    def test_is_noun_phrase(self):
        questions_answers_nps = [  # Note all these have been manually inspected.
            ("A person is cleaning a window with _____.", "18 inch squeegee", True),
            ("Two strong men are fighting with each other in _____.", "a battle of fists", True),
            # ("a beam", True),
            ("Two strong men are fighting with each other in _____.", "a boxing arena", True),
            # ("a boxing match", True),
            # ("a boxing ring with george foreman knocking down his opponent", True),
            # ("a boxing ring", True),
            # ("a boxing stadium", True),
            # ("a boy", True),
            # ("a casual player", True),
            # ("a cleaning instrument", True),
            # ("a cleaning utensil", True),
            # ("a crowded venue", True),
            # ("a fight", True),
            # ("a flashlight of some sort", True),
            # ("a flashlight", True),
            # ("a handheld flashlight", True),
            # ("a headlamp on the caver", True),
            # ("a headlamp", True),
            # ("a heated battle", True),
            # ("a helmet-mounted light", True),
            # ("a hook", True),
            # ("a horrible fashion", True),
            # ("a keyboard enthusiast", True),
            # ("a keyboard hobbyist", True),
            # ("a keyboard instructor", True),
            # ("a keyboardist", True),
            # ("a lamp used by the adventurer", True),
            # ("a lamp", True),
            # ("a light", True),
            # ("a long-poled squeegee", True),
            # ("a male instructor", True),
            # ("a man holding a flashlight", True),
            # ("a man shows us how to play a piano and", False),
            # ("a man", True),
            # ("a mini torchlight", True),
            # ("a mop", True),
            # ("a packed arena", True),
            # ("a person", True),
            # ("a phone", True),
            ("_____ gives a demonstration of a song on piano.", "A pianist shows how to get a different sound and",
             False),
            # ("a pianist", True),
            # ("a piano instructor", True),
            # ("a piano player", True),
            # ("a piano teacher", True),
            # ("a pick", True),
            # ("a pocket flashlight", True),
            # ("a portable device", True),
            # ("a professional competition", True),
            # ("a professional", True),
            # ("a protective layer of styrofoam", True),
            # ("a ring", True),
            # ("a rubber blade on a pole", True),
            # ("a rubber squeegee", True),
            # ("a searchlight", True),
            # ("a small flashlight", True),
            # ("a sponge", True),
            # ("a squeegee", True),
            # ("a sweeper", True),
            # ("a tactical flashlight", True),
            # ("a teacher", True),
            # ("a tool on a stick", True),
            # ("a tool", True),
            # ("a torchlight", True),
            # ("a tutor", True),
            # ("a wagtail squeegee", True),
            # ("a youtuber", True),
            # ("ample protection", True),
            # ("an apparatus", True),
            # ("an arena", True),
            # ("an attempt to see who wins", True),
            # ("an axe", True),
            # ("an ice climbing pick", True),
            # ("an ice pick", True),
            # ("an led lamp", True),
            # ("an led torch", True),
            # ("an unsteady flashlight", True),
            # ("an youtuber", True),
            # ("applying", True),
            # ("arranger", True),
            # ("artificial light", True),
            # ("artist", True),
            # ("athleticism", True),
            # ("automotive maintenance information", True),
            # ("bladed shoes", True),
            # ("boots with metal prongs", True),
            # ("boots with spikes", True),
            # ("boxing match", True),
            # ("boxing", True),
            # ("broom with cloth at the end", True),
            # ("brush", True),
            # ("brute strength", True),
            # ("car parts", True),
            # ("cautioning how to hammer", True),
            # ("cleats", True),
            # ("climbing boots", True),
            # ("climbing gear", True),
            # ("climbing implements", True),
            # ("competitive boxing", True),
            # ("competitive run", True),
            # ("competitive spirit", True),
            # ("composer", True),
            # ("crampons", True),
            # ("cushioning material", True),
            # ("downhill skiing", True),
            # ("elegance", True),
            # ("enthralling run", True),
            # ("escapades", True),
            # ("event time", True),
            # ("extra protection", True),
            # ("flashlight on helmet", True),
            # ("flashlight", True),
            # ("flat metal objects", True),
            # ("foam blocks and sheets", True),
            # ("foam fillers", True),
            # ("foam sheets", True),
            # ("foam", True),
            # ("front of the audience", True),
            # ("gavin degraw", True),
            # ("hammering in", True),
            # ("he wants to hammer it in", False),
            # ("headlamp", True),
            # ("headlight", True),
            # ("heated combat", True),
            # ("helmet light", True),
            # ("helmet torch", True),
            # ("his actions", True),
            # ("his boots", True),
            # ("his feet", True),
            # ("his hands and feet", True),
            # ("his intentions", True),
            # ("his methods", True),
            # ("his own hands", True),
            # ("his plan", True),
            # ("how it works", True),
            # ("how to add a wheel stud", True),
            # ("how to attach", True),
            # ("how to change a tire", True),
            # ("how to change a wheel stud", True),
            # ("ice boots", True),
            # ("ice climbing boots", True),
            # ("ice grippers", True),
            # ("ice picks", True),
            # ("kicking motions", True),
            # ("loose styrofoam packing closely", True),
            # ("man", True),
            # ("mop", True),
            # ("musician", True),
            # ("nuts", True),
            # ("olympic run", True),
            # ("olympic skiing event", True),
            # ("order to see which one will be the victor", True),
            # ("package stuffing", True),
            # ("packaging cushion", True),
            # ("packaging foam", True),
            # ("packaging material", True),
            # ("packing foam", True),
            # ("packing material", True),
            # ("packing materials", True),
            # ("padding material", True),
            # ("padding", True),
            # ("pianist", True),
            # ("pieces of styrofoam", True),
            # ("pink styrofoam", True),
            # ("practice run", True),
            # ("properly installing washers", True),
            # ("protection", True),
            # ("pulling on the washer", True),
            # ("pulling", True),
            # ("putting it on the stud", True),
            # ("race", True),
            # ("raw footage", True),
            # ("recording", True),
            # ("repairing a tire", True),
            # ("ring", True),
            # ("safety cushion", True),
            # ("scraper on a pole", True),
            # ("several styrofoam products", True),
            # ("shoe pics", True),
            # ("shoes", True),
            # ("shorts", True),
            # ("ski run", True),
            # ("skiing course", True),
            # ("slalom", True),
            # ("slow-motion video", True),
            # ("snow boots", True),
            # ("snow shoes", True),
            # ("some padding", True),
            # ("some styrofoam", True),
            # ("somebody on camera", True),
            # ("special spiked boots", True),
            # ("spiked boots", True),
            # ("spikes", True),
            # ("squeegee on a pole", True),
            # ("squeegee", True),
            # ("styrofoam packing", True),
            # ("styrofoam to act as a safeguard", True),
            # ("styrofoam", True),
            # ("telescoping squeegee", True),
            # ("the 240x wheel stud changing process", True),
            # ("the boxing championship", True),
            # ("the boxing ring", True),
            # ("the championship", True),
            # ("the correct installation method", True),
            # ("the moves", True),
            # ("the musician", True),
            # ("the objects being applied", True),
            # ("the person in the video", True),
            # ("the person", True),
            # ("the pianist", True),
            # ("the pieces used", True),
            # ("the pointed end of an ice axe", True),
            # ("the poise", True),
            # ("the process", True),
            # ("the right way to install it", True),
            # ("the ring", True),
            # ("the showmanship", True),
            # ("the skier is a prime example", False),
            # ("the squared circle", True),
            # ("the tools used", True),
            # ("the trials", True),
            # ("the way to do it", True),
            # ("thermocol sheets", True),
            # ("this is a slow motion view", False),
            # ("this is a stunning performance", False),
            # ("this is one example", False),
            # ("this video is a slow motion angle", False),
            # ("torch", True),
            # ("tricks", True),
            # ("turning", True),
            # ("turns", True),
            # ("video", True),
            # ("view of the camera", True),
            # ("washers", True),
            # ("water and squeegee", True),
            # ("window cleaner", True),
            # ("window cleaning device ona pole", True),
            # ("window cleaning tools", True),
            # ("wiper", True),
            # ("with gloves on", False),
            # ("you can see that the pianist", False),
            # ("you can see this can hurt the legs and knees", False),

            ("_____ a dog.", "A cat and", False),
            ("_____ how he puts together a small finished wood shelf.", "A man video tapes", False),
        ]

        texts_starts_ends_and_nps = [(question.replace("_____", answer), (start := question.index("_____")),
                                      start + len(answer), np)
                                     for question, answer, np in questions_answers_nps]

        spacy_model = create_spacy_model(prefer_gpu=True)
        docs = spacy_model.pipe(text for text, _, _, _ in texts_starts_ends_and_nps)

        actual_nps = [is_noun_phrase_like(doc, start, end)
                      for doc, (_, start, end, _) in zip(docs, texts_starts_ends_and_nps)]
        expected_nps = [np for _, _, _, np in texts_starts_ends_and_nps]

        self.assertEqual(expected_nps, actual_nps)
