name: lqam
channels:
  - pytorch
  - defaults
dependencies:
  - pip:
    - overrides==2.8.0
    - pytorch-lightning==0.7.3
    - tensorboard==2.2.0
    - tokenizers==0.5.2
    - tqdm==4.43.0
    - transformers==2.8.0
  - cudatoolkit=10.1.243
  - cudnn==7.6.5
  - numpy=1.18.1
  - pip=20.0
  - python=3.8
  - pytorch=1.4.0
  - torchvision=0.5.0
