name: lqam
channels:
  - pytorch
  - defaults
dependencies:
  - pip:
    - overrides==3.1.0
    - pytorch-lightning==0.7.3
    - rarfile==4.0
    - tensorboard==2.4.0
    - transformers==4.0.0
  - boto3=1.16.29
  - botocore=1.19.29
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - nltk=3.5
  - numpy=1.18.1
  - pandas=1.1.3
  - pip=20.3
  - python=3.8
  - pytorch=1.4.0
  - torchvision=0.5.0
  - tqdm=4.54.0
