name: lqam
channels:
  - pytorch
dependencies:
  - pip:
    - cupy-cuda110==8.3.0  # For spaCy.
    - moviepy==1.0.3
    - python-youtube==0.6.4
    - spacy-nightly[cuda110]==3.0.0rc2  # Use this version of spaCy because we want to use the model `en_core_web_trf`.
    # This version of spacy-transformers supports transformers v4.2, and it's needed for the spaCy model we want.
    - git+https://github.com/explosion/spacy-transformers@v1.0.0rc2
    # We could use the Anaconda channel "HuggingFace".
    # However, `tokenizers` was compiled with glibc 2.18, while Great Lakes has 2.17.
    # There are some non-popular glibc packages available in Anaconda, but Python needs to be linked to it as well.
    # This is cumbersome, so we just use pip.
    - transformers==4.2.0
  - boto3=1.16.29
  - botocore=1.19.29
  - csvkit=1.0.5
  - cudatoolkit=11.0.221
  - nvidia::cudnn=8.0.4  # cuDNN 8 isn't available from the default channel yet.
  - numpy=1.18.1
  - conda-forge::overrides=3.1.0
  - pandas=1.1.3
  - pip=20.3
  - python=3.8
  - pytorch=1.7.1
  - conda-forge::pytorch-lightning=1.1.0
  - conda-forge::rarfile=4.0
  - conda-forge::tensorboard=2.4.0
  - torchvision=0.8.2
  - tqdm=4.54.0
  - conda-forge::youtube-dl=2021.1.8
