name: lqam
channels:
  - pytorch
  - defaults
dependencies:
  - pip:
    # We could use the Anaconda channel "HuggingFace".
    # However, `tokenizers` was compiled with glibc 2.18, while Great Lakes has 2.17.
    # There are some non-popular glibc packages available in Anaconda, but Python needs to be linked to it as well.
    # This is cumbersome, so we just use pip:
    - moviepy==1.0.3
    - transformers==4.1.1
  - boto3=1.16.29
  - botocore=1.19.29
  - cudatoolkit=11.0.221
  - nvidia::cudnn=8.0.4  # cuDNN 8 isn't available from the default channel yet.
  - numpy=1.18.1
  - conda-forge::overrides=3.1.0
  - pandas=1.1.3
  - pip=20.3
  - python=3.8
  - pytorch=1.7.1
  - conda-forge::pytorch-lightning=1.1.0
  - conda-forge::rarfile=4.0
  - spacy=2.3.5
  - conda-forge::tensorboard=2.4.0
  - torchvision=0.8.2
  - tqdm=4.54.0
  - conda-forge::youtube-dl=2021.1.8
