name: lqam
variables:
  PYTHONPATH: .
dependencies:
  - pip:
    -            moviepy==1.0.*
    -            python-youtube==0.6.*
    -            sentencepiece==0.1.*  # For the "google/t5-v1_1-" models.
    # We could use the Anaconda channel "HuggingFace".
    # However, `tokenizers` was compiled with glibc 2.18, while Great Lakes cluster has 2.17.
    # See https://github.com/huggingface/tokenizers/issues/585
    # There are some non-popular glibc packages available in Anaconda, but Python needs to be linked to it as well.
    # This is cumbersome, so we just use pip.
    -            transformers==4.2.*
  - conda-forge::adjusttext=0.7
  - conda-forge::awscli=1
  -              boto3=1
  -              botocore=1
  -              cudatoolkit=11.0
  - conda-forge::cupy>=5.0.0b4,<9  # For spaCy.
  -              jq=1
  -              jupyter=1
  -              matplotlib=3
  -              numpy=1
  - conda-forge::overrides=3
  -              pandas=1
  -              pip=22
  -              python=3.9
  -     pytorch::pytorch=1.7*=*cuda*
  - conda-forge::pytorch-lightning=1.1
  - conda-forge::rarfile=4
  -              seaborn=0.11
  -              scikit-learn=1
  -              scikit-learn-intelex
  - conda-forge::sentence-transformers=2.2
  - conda-forge::spacy=3
  - conda-forge::tensorboard=2
  -     pytorch::torchvision=0.8
  -              tqdm=4
  - conda-forge::youtube-dl=2021.1.8
