name: lqam
channels:
  - pytorch
dependencies:
  - pip:
    - moviepy==1.0.3
    - python-youtube==0.6.4
    # We could use the Anaconda channel "HuggingFace".
    # However, `tokenizers` was compiled with glibc 2.18, while Great Lakes has 2.17.
    # See https://github.com/huggingface/tokenizers/issues/585
    # There are some non-popular glibc packages available in Anaconda, but Python needs to be linked to it as well.
    # This is cumbersome, so we just use pip.
    - transformers==4.2.2
    - sentencepiece==0.1.95
  - conda-forge::awscli=1.18
  - boto3=1.16.29
  - botocore=1.19.29
  - cudatoolkit=11.0.221
  - conda-forge::cupy>=5.0.0b4,<9.0.0  # For spaCy.
  - conda-forge::cudnn=8.0.5
  - jq=1.6
  - jupyter=1.0.0
  - matplotlib=3.3.2
  - numpy=1.18.1
  - conda-forge::overrides=3.1.0
  - pandas=1.1.3
  - pip=21.0
  - python=3.8
  - pytorch=1.7.1
  - conda-forge::pytorch-lightning=1.1.6
  - conda-forge::rarfile=4.0
  - seaborn=0.11.1
  - conda-forge::spacy=3.0.0
  - conda-forge::tensorboard=2.4.1
  - torchvision=0.8.2
  - tqdm=4.54.0
  - conda-forge::youtube-dl=2021.1.8
