name: CI
on:
  push
#    branches: TODO: add again
#    - master
#  pull_request:
#    branches:
#    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-
    # Don't cache more stuff because it takes more time than to install the Conda env.
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: lqam
        environment-file: environment.yml
    - name: Load HuggingFace cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/huggingface  # transformers' downloaded models.
        key: ${{ runner.os }}-huggingface-${{ hashFiles('**/*') }}
        restore-keys: |
          ${{ runner.os }}-huggingface-
    - name: Run tests
      run: python -m unittest discover .
