name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}  # So the conda activation is kept.
    steps:
    - uses: actions/checkout@v2
    # I followed https://github.com/conda-incubator/setup-miniconda#caching but Conda caching still doesn't work.
    # So it's disabled because it'd take more time otherwise.
#    - name: Cache Conda
#      uses: actions/cache@v2
#      with:
#        path: ~/conda_pkgs_dir
#        key:
#          ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
#        restore-keys: |
#          ${{ runner.os }}-conda-
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: lqam
        environment-file: environment.yml
#        use-only-tar-bz2: true  # For Conda caching.
    - name: Load HuggingFace cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/huggingface  # transformers' downloaded models.
        key: ${{ runner.os }}-huggingface-${{ hashFiles('**/*') }}
        restore-keys: |
          ${{ runner.os }}-huggingface-
    - name: Download spaCy model
      run: spacy download en_core_web_trf
    - name: Run tests
      run: python -m unittest discover .
    - name: Evaluate text-only T5 baseline
      run: PYTHONPATH=. ./scripts/evaluate_text_only_baseline.py
